import type { Project } from "./types"
import { landingCounts, landingZones, sequenceDuration } from "./engine"

// JSON motion brief, schema-compatible with the Bird Motion Mapper pipeline.
export function buildMotionBriefJson(project: Project) {
  return {
    schema_version: "1.0",
    project: {
      name: project.name,
      captured_at: new Date().toISOString(),
      viewport: project.viewport,
      output_variant: project.activeVariant,
    },
    anchors: project.sequences.flatMap((sequence, sequenceIndex) =>
      landingZones(sequence).map((landing, landingIndex) => ({
          id: `a-${sequenceIndex + 1}-${landingIndex + 1}`,
          name: `${sequence.name} landing ${landingIndex + 1}`,
          role: "Landing zone",
          normalized_center: { x: +(landing.x + landing.w / 2).toFixed(4), y: +(landing.y + landing.h / 2).toFixed(4) },
          normalized_size: { w: +landing.w.toFixed(4), h: +landing.h.toFixed(4) },
          flock_interaction: "Land",
          dwell_seconds: sequence.dwellSeconds,
        })),
    ),
    paths: project.sequences.map((s) => ({
      id: s.id,
      name: s.name,
      treatment: s.treatment,
      duration_seconds: s.durationSeconds,
      effective_duration_seconds: +sequenceDuration(s).toFixed(3),
      dwell_seconds: s.dwellSeconds,
      arrival_mode: s.arrivalMode,
      landing_event_count: landingZones(s).length,
      seamless_loop: s.loopPath,
      perch_count: landingCounts(s).perch,
      gather_count: landingCounts(s).gather,
      fly_through_count: landingCounts(s).flyThrough,
      speed_model: "constant arc-length through ordered landing waypoints",
      speed_multiplier: s.speedMultiplier ?? 1,
      bird_size_scale: s.sizeScale ?? 1,
      formation_spacing_scale: s.spacingScale ?? 1.8,
      foreground_bird_count: s.foregroundBirdCount ?? 0,
      bird_count: s.birdCount,
      foreground_size_boost: s.foregroundBoost ?? 1,
      depth_direction: s.depthDirection ?? "Flat plane",
      depth_strength: s.depthStrength ?? 0.75,
      bird_artwork: {
        name: (s.birdTemplate ?? project.birdTemplate).name,
        kind: (s.birdTemplate ?? project.birdTemplate).kind,
        frames: (s.birdTemplate ?? project.birdTemplate).frames.length,
      },
      density: s.density,
      wing_intensity: s.wingIntensity,
      entry: s.entry,
      exit: s.exit,
      raw_points: s.points.map((p) => ({ x: +p.x.toFixed(6), y: +p.y.toFixed(6) })),
      notes: s.notes,
      theme_colors: { light: s.lightColor, dark: s.darkColor },
    })),
    scene: { kind: project.scene.kind, compositable: project.scene.kind === "image" },
    default_bird_template: { name: project.birdTemplate.name, kind: project.birdTemplate.kind, frames: project.birdTemplate.frames.length },
    style: {
      ink_color: project.style.inkColor,
      transparent_background: project.style.transparentBackground,
      source_contours_only: true,
    },
  }
}

export function buildDesignerBriefMarkdown(project: Project): string {
  const lines: string[] = []
  lines.push(`# ${project.name} — Bird Motion Brief`, "")
  lines.push(`Output variation: ${project.activeVariant}`)
  lines.push(`Viewport: ${project.viewport.width} x ${project.viewport.height}`)
  lines.push(`Ink color: ${project.style.inkColor}`)
  lines.push(`Background: ${project.style.transparentBackground ? "transparent" : project.style.backgroundColor}`)
  lines.push(`Scene source: ${project.scene.kind} · Bird template: ${project.birdTemplate.name} (${project.birdTemplate.kind})`, "")
  project.sequences.forEach((s, i) => {
    lines.push(`## ${i + 1}. ${s.name}`, "")
    lines.push(`- Treatment: **${s.treatment}**`)
    lines.push(`- Birds: ${s.birdCount} (${s.density} preset) · Wing beat: ${s.wingIntensity}`)
    lines.push(`- Enter: ${s.entry} · Exit: ${s.exit}`)
    lines.push(`- Base timeline: ${s.durationSeconds}s · Speed: ${(s.speedMultiplier ?? 1).toFixed(2)}x · Dwell: ${s.dwellSeconds}s`)
    lines.push(`- Seamless background loop: ${s.loopPath ? "yes — closed path, landing disabled" : "no"}`)
    lines.push(`- Landing events: ${landingZones(s).length} · Birds at each stop: ${landingCounts(s).perch} perch · ${landingCounts(s).gather} gather · ${landingCounts(s).flyThrough} fly through`)
    lines.push(`- Bird size: ${(s.sizeScale ?? 1).toFixed(2)}x · Spacing: ${(s.spacingScale ?? 1.8).toFixed(2)}x · Depth: ${s.depthDirection ?? "Flat plane"} (${(s.depthStrength ?? 0.75).toFixed(2)}x)`)
    lines.push(`- Foreground birds: ${s.foregroundBirdCount ?? 0} · Foreground boost: ${(s.foregroundBoost ?? 1).toFixed(2)}x`)
    lines.push(`- Bird artwork: ${(s.birdTemplate ?? project.birdTemplate).name} (${(s.birdTemplate ?? project.birdTemplate).frames.length} file(s))`)
    landingZones(s).forEach((lz, landingIndex) => {
      lines.push(
        `- Landing ${landingIndex + 1}: center (${(lz.x + lz.w / 2).toFixed(2)}, ${(lz.y + lz.h / 2).toFixed(2)}), size ${(lz.w * 100).toFixed(0)}% x ${(lz.h * 100).toFixed(0)}%`,
      )
    })
    lines.push(`- Path points: ${s.points.map((p) => `(${p.x.toFixed(2)}, ${p.y.toFixed(2)})`).join(" → ")}`)
    if (s.notes.trim()) lines.push(`- Notes: ${s.notes.trim()}`)
    lines.push("")
  })
  return lines.join("\n")
}

export function buildApplicationGuide(project: Project, exportBaseName: string): string {
  const sceneName = project.scene.kind === "none" ? "the destination page background" : project.scene.name
  const width = project.viewport.width
  const height = project.viewport.height
  return [
    `# Apply ${exportBaseName} to ${sceneName}`,
    "",
    "This handoff is written for an implementation agent. Preserve the authored timing, viewport, alpha, and alignment; do not redraw the flock with CSS or substitute a GIF.",
    "",
    "## Choose the correct asset",
    "",
    `- Light-theme Chrome/Firefox transparency: \`${exportBaseName}-light-alpha.webm\` (VP9 alpha).`,
    `- Dark-theme Chrome/Firefox transparency: \`${exportBaseName}-dark-alpha.webm\` (VP9 alpha).`,
    `- Light-theme Apple transparency: \`${exportBaseName}-light-alpha.mov\` (HEVC with alpha).`,
    `- Dark-theme Apple transparency: \`${exportBaseName}-dark-alpha.mov\` (HEVC with alpha).`,
    `- Opaque, already composited delivery: \`${exportBaseName}.mp4\` (H.264). Do not overlay this file on the same background again.`,
    "- Editing master: the transparent PNG sequence or ProRes 4444 intermediate.",
    "",
    "HEIC is a still-image/image-sequence container. For transparent motion on Apple platforms, use HEVC with alpha in a MOV file.",
    "",
    "## Theme color contract",
    "",
    "Bird color is authored to change with the destination site's light/dark theme. Do not ship one palette for both themes and do not recolor the video with a guessed CSS filter. The complete handoff includes synchronized light and dark renders. Keep both source pairs and let CSS select the appropriate video.",
    "",
    "## Web overlay structure",
    "",
    "```html",
    '<div class="flock-scene">',
    '  <div class="flock-scene__background"><!-- selected background/card/page --></div>',
    '  <video class="flock-scene__birds flock-scene__birds--light" autoplay muted loop playsinline aria-hidden="true">',
    `    <source src="/${exportBaseName}-light-alpha.mov" type='video/quicktime; codecs="hvc1"'>`,
    `    <source src="/${exportBaseName}-light-alpha.webm" type='video/webm; codecs="vp9"'>`,
    "  </video>",
    '  <video class="flock-scene__birds flock-scene__birds--dark" autoplay muted loop playsinline aria-hidden="true">',
    `    <source src="/${exportBaseName}-dark-alpha.mov" type='video/quicktime; codecs="hvc1"'>`,
    `    <source src="/${exportBaseName}-dark-alpha.webm" type='video/webm; codecs="vp9"'>`,
    "  </video>",
    "</div>",
    "```",
    "",
    "```css",
    ".flock-scene { position: relative; overflow: hidden; }",
    ".flock-scene__background { position: relative; z-index: 0; }",
    ".flock-scene__birds {",
    "  position: absolute; inset: 0; z-index: 1;",
    "  width: 100%; height: 100%; object-fit: contain;",
    "  pointer-events: none; background: transparent;",
    "}",
    ".flock-scene__birds--dark { display: none; }",
    ".dark .flock-scene__birds--light, [data-theme='dark'] .flock-scene__birds--light { display: none; }",
    ".dark .flock-scene__birds--dark, [data-theme='dark'] .flock-scene__birds--dark { display: block; }",
    "@media (prefers-color-scheme: dark) {",
    "  :root:not(.light):not([data-theme='light']) .flock-scene__birds--light { display: none; }",
    "  :root:not(.light):not([data-theme='light']) .flock-scene__birds--dark { display: block; }",
    "}",
    "```",
    "",
    "## Alignment contract",
    "",
    `- Authored viewport: ${width} x ${height} (${(width / Math.max(1, height)).toFixed(4)}:1).`,
    "- Keep the video and selected background inside the same aspect-ratio box.",
    "- Use the same `object-fit` value for the reference image and video. Murmur previews uploaded images with `contain`.",
    "- Do not crop or independently scale the video after landing coordinates have been approved.",
    "- HTML/CSS and URL scenes are alignment references only; use the transparent output over the live implementation.",
    "",
    "## Validation checklist",
    "",
    "1. Confirm the first and last frames do not flash an opaque rectangle.",
    "2. Confirm every authored landing stop plays approach → settle/perch → launch at constant route speed, while non-participants fly through.",
    "3. Test Safari with the HEVC-alpha MOV and Chrome/Firefox with VP9-alpha WebM.",
    "4. Honor `prefers-reduced-motion` by pausing or hiding decorative autoplay video.",
    "5. Toggle the site's actual light/dark theme and confirm the matching bird palette appears without moving or cropping.",
    "6. Keep the MP4 fallback separate because it already contains an opaque background.",
    "",
    "```css",
    "@media (prefers-reduced-motion: reduce) { .flock-scene__birds { display: none !important; } }",
    "```",
    "",
  ].join("\n")
}

export function buildBirdArtworkAgentPrompt(): string {
  return [
    "# Production prompt: authored bird animation source for Murmur",
    "",
    "You are producing source artwork for the Murmur bird-flock motion builder. Follow this contract exactly. The receiving agent must be able to use the files without redrawing, tracing, re-rigging, renaming, or guessing their order.",
    "",
    "## Non-negotiable visual direction",
    "",
    "- Use the supplied artist reference as the source of truth. Preserve its open marine-blue line work, uneven hand-drawn curves, sparse mark economy, asymmetry, center notch, and layered wing strokes.",
    "- Do not substitute a generic gull, symmetric V, logo icon, filled silhouette, detailed anatomical bird, white outline, or parametric two-line symbol.",
    "- If exact source pixels are supplied, extract and clean those pixels; do not regenerate their geometry.",
    "- Every animation frame in one bundle must depict the same bird identity. Wing and body pose may change naturally, but the contour must not morph into a different bird.",
    "- Keep the bird facing the same direction in every frame. Do not flip individual frames.",
    "- Declare that consistent source direction as `left` or `right` in the manifest. Murmur uses this metadata to mirror the art automatically from the user's Enter, drawn path, and Exit choices; it does not force every flock to fly leftward.",
    "- Do not synthesize motion by rotating the whole bird, hinging two halves of one still, or replacing the artist's delivered poses with a procedural V shape.",
    "",
    "## Best input: 32 transparent PNGs per identity",
    "",
    "Each usable bird identity needs one eight-frame flight cycle and, when that bird may land, three matched eight-frame action tracks: approach, perch/settle, and launch/flyoff. That is 32 transparent PNGs per identity. A flock of 1–8 visible birds can reuse one identity with different timing, scale, and path offsets; it does not require 1–8 different artwork files.",
    "",
    "```text",
    "murmur-bird-artwork/",
    "├── README.md",
    "├── bird-01/",
    "│   ├── manifest.json",
    "│   ├── flight/",
    "│   │   ├── 01_neutral_settle.png",
    "│   │   ├── 02_upstroke_lift.png",
    "│   │   ├── 03_upstroke_peak.png",
    "│   │   ├── 04_upstroke_return.png",
    "│   │   ├── 05_level_glide.png",
    "│   │   ├── 06_downstroke_drive.png",
    "│   │   ├── 07_downstroke_peak.png",
    "│   │   └── 08_recovery.png",
    "│   ├── 01_landing_approach/  # 8 frames, approach to touchdown-ready",
    "│   ├── 02_perch_settle_hold/ # 8 frames, contact to restrained hold",
    "│   └── 03_launch_flyoff/     # 8 frames, crouch to clear flight",
    "├── bird-02/                 # optional second identity; same structure",
    "├── qa/",
    "│   ├── bird-01-flight-contact-sheet.png",
    "│   ├── bird-01-action-contact-sheet.png",
    "│   ├── bird-01-alpha-check.png",
    "│   └── bird-01-motion-review.mp4",
    "└── source/                    # optional reproducibility files",
    "    ├── build_frames.py",
    "    └── verify_frames.sh",
    "```",
    "",
    "Repeat the structure only for genuinely distinct identities. Deliver the strongest 6–10 identities rather than padding the set with redundant pre-flipped or pre-stretched versions. Murmur mirrors direction and applies path banking at runtime. Every track must remain one bird identity through one coherent action; do not mix birds or create unrelated drawings. Prefix every pose with `01_`, `02_`, `03_` … so ordering is deterministic.",
    "",
    "## Files Murmur accepts as bird input",
    "",
    "- Preferred runtime source: numbered transparent PNGs (`.png`) with straight alpha.",
    "- A ZIP is a transport wrapper for the complete folder; the PNGs and manifest inside are the source of truth.",
    "- Package one bird identity per ZIP for the lowest-friction import. That ZIP may contain the manifest at its root or inside one `bird-01/` folder; do not mix several identities into one import bundle.",
    "- A single transparent WebP or SVG may be used only as a static fallback. It is not equivalent to an authored animation cycle.",
    "- Do not use JPEG: it has no alpha channel.",
    "- MP4, WebM, and MOV are QA or delivery formats, not editable bird source. They may be included as previews, but never instead of the numbered PNGs.",
    "- Do not give Murmur `.py`, `.sh`, `.mp4`, `.webm`, or `.mov` as bird frames. Python and shell files are optional reproducibility sources.",
    "",
    "## Pixel and alignment contract",
    "",
    "- Preferred frame size: 1600 px wide. Minimum: 960 px wide. Use the natural aspect ratio; do not stretch or upscale a smaller source to claim compliance.",
    "- Within each eight-frame track, keep the center notch/body anchor at the exact same pixel coordinate. Flight and action tracks may use different canvas sizes, but each canvas and anchor must be declared and the normalized anchor must remain aligned across the transition.",
    "- Keep at least 80 transparent pixels of padding on every side; no stroke may touch or clip at the canvas edge in any pose.",
    "- Raster coordinate convention is top-left origin. `up` must point toward the top edge of the PNG. Strip EXIF/orientation transforms; every file must decode already upright.",
    "- Background pixels must have alpha 0. Do not bake in white, black, checkerboard, shadows, glow, matte, or a scene background.",
    "- Use one consistent ink color, recommended `#043A78`. Preserve antialiased edge alpha.",
    "- Canvas size, scale, orientation, and anchor must remain identical within one track. Natural pose changes are allowed, but the anchor may not jump between frames or when Murmur switches tracks.",
    "- The action canvas anchor is the external landing target. Do not draw a branch, wire, ledge, shadow, or background into the bird art.",
    "",
    "## `manifest.json` schema",
    "",
    "```json",
    "{",
    "  \"schema_version\": \"1.0\",",
    "  \"sets\": [",
    "    {",
    "      \"id\": \"bird-01\",",
    "      \"name\": \"Artist contour - hero\",",
    "      \"direction\": \"left\",",
    "      \"canvases\": {",
    "        \"flight\": { \"width\": 2496, \"height\": 1504, \"anchor\": { \"x\": 1248, \"y\": 752 } },",
    "        \"action\": { \"width\": 2144, \"height\": 1630, \"anchor\": { \"x\": 1072, \"y\": 815 } }",
    "      },",
    "      \"up_direction\": \"canvas_top\",",
    "      \"orientation_metadata\": \"stripped\",",
    "      \"ink_color\": \"#043A78\",",
    "      \"tracks\": {",
    "        \"flight\": [\"01_neutral_settle.png\", \"02_upstroke_lift.png\", \"03_upstroke_peak.png\", \"04_upstroke_return.png\", \"05_level_glide.png\", \"06_downstroke_drive.png\", \"07_downstroke_peak.png\", \"08_recovery.png\"],",
    "        \"approach\": [\"01_approach_glide.png\", \"02_brake_lift.png\", \"03_brake_peak.png\", \"04_brake_release.png\", \"05_contact_lower.png\", \"06_touchdown.png\", \"07_settle_fold.png\", \"08_perch_ready.png\"],",
    "        \"perch\": [\"01_perch_contact.png\", \"02_wing_fold.png\", \"03_settle_1.png\", \"04_settle_2.png\", \"05_hold_1.png\", \"06_micro_lift.png\", \"07_hold_2.png\", \"08_ready_launch.png\"],",
    "        \"launch\": [\"01_crouch_ready.png\", \"02_release_lift.png\", \"03_launch_drive.png\", \"04_launch_peak.png\", \"05_clear_perch.png\", \"06_flyoff_glide.png\", \"07_flyoff_drive.png\", \"08_depart_recovery.png\"]",
    "      },",
    "      \"source_method\": \"authored aligned PNG sequences; direct chronological playback\"",
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "## Required QA",
    "",
    "1. Verify every PNG has an alpha channel and contains both fully transparent and visible pixels.",
    "2. Verify each track's eight files have identical pixel dimensions and one fixed body/landing anchor. Record flight and action canvases separately when their sizes differ.",
    "3. Produce chronological contact sheets for flight, approach, perch, and launch. Labels must include both frame number and action name.",
    "4. Produce native-scale checks on both white and dark backgrounds and prove no contour is clipped or pixelated.",
    "5. Produce a short MP4 or WebM preview only for human review; it is not a Murmur input.",
    "6. Preview the flight track at approximately 6 fps, 8 fps, and 10 fps. The sequence must visibly pass through both upstroke and downstroke peaks without reversing, freezing, or mechanical whole-image rotation.",
    "7. Preview approach to perch to launch as one continuous action. Perched frames must be restrained and must not repeat the full flight flap.",
    "8. Reject the delivery if it reads as repeated V marks, if identities morph, if alpha is opaque, if `up` is ambiguous, if the anchor jumps, or if any contour is clipped.",
    "",
    "## How the recipient imports the result",
    "",
    "In Murmur, select Flock 1, click the Bird template preview card, and choose that identity's ZIP. Murmur validates the manifest, alpha, file order, canvas sizes, and all four tracks, then reports `Passed: 8 flight poses plus 24 matched landing-action poses`. Add/select Flock 2 and import a different one-identity ZIP only when the composition needs it. Each Flock tab retains its own artwork after reload and in every export. The Exact birds control sets how many birds are visible; the artwork files describe poses for one identity, not the visible bird count. Murmur plays ordered source frames directly, applies independent phase timing per bird, mirrors direction from the actual path, and switches to the matched action tracks for landing and launch.",
    "",
    "Return one directly importable ZIP per identity plus the unzipped files. Report the exact QA results and any deviation from this contract; do not silently improvise.",
    "",
  ].join("\n")
}
